# Generated by Django 5.0.7 on 2024-07-16 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Модель велосипеда')),
                ('bike_type', models.CharField(choices=[('urban', 'Городские'), ('road', 'Шоссейные'), ('off-reoad', 'Внедорожные')], max_length=128, verbose_name='Тип велосипеда')),
                ('status', models.CharField(choices=[('available', 'Доступен для аренды'), ('unavailable', 'Арендован')], default=('available', 'Доступен для аренды'), max_length=64, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='BikeRentalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start', models.DateTimeField(auto_now=True, verbose_name='Время начала аренды')),
                ('rental_end', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания аренды')),
                ('active_status', models.BooleanField(default=True, verbose_name='Статус аренды')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_rental.bikemodel', verbose_name='Модель велосипеда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
