# Generated by Django 5.0.7 on 2024-07-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerentalmodel',
            name='active_status',
        ),
    ]
