# Generated by Django 5.0.7 on 2024-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0002_remove_bikerentalmodel_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerentalmodel',
            name='rental_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала аренды'),
        ),
    ]
